name: mgtorch
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.8
  - pip
  - cudatoolkit=11.3
  - matplotlib==3.2.2
  - pytorch==1.11
  - torchvision==0.12
  - pip:
    - einops==0.4.1
    - ipykernel==6.15.0
    - jupyter==1.0.0
    - Pillow==9.1.0
    - ml-collections==0.1.1
    - requests==2.27.1
    - tqdm==4.64.0